### ISSUE TITLE
Passing of paths with spaces not working on windows

### ISSUE THREAD

**Issue by Terminatorthre** [Southclaws/restic-robot#12]
Hi,

while experimenting with restic-robot for windows server 2022 backup, we noticed issues with paths that contain spaces.
While restic itself has no issues with restic.exe backup "C:\FTP TASKS" I could not find a working way with restic-robot.
I tried

- C:\FTP TASKS
- "C:\FTP TASKS"
- "`"C:\FTP TASKS`""
- C:\FTP^TASKS

Is there a working solution somewhere that I could not find or is this a real bug? This might be even more complicated when multiple paths containing spaces have to be passed.

Any further information I can provide to help narrow this down? I think this should be quite easy to replicate.

**Comment by Terminatorthre** [comment]
I have created some code to better handle paths with spaces and also allow multipe paths with spaces. Please check the pull request carefully, as I am not a programmer
https://github.com/Southclaws/restic-robot/pull/13

**Comment by Southclaws** [comment]
Hey, thanks for this! I'll give this a look some time this week 👍
