### ISSUE TITLE
Multiple repos, backup paths, servers etc?

### ISSUE THREAD

**Issue by xpufx** [Southclaws/restic-robot#22]
As far as I can see only one configuration is supported. In my use case with plain restic I am backing up to multiple servers. I'm also using multiple repos on the same server (in order to better handle deduplication vs locking ). These require different configurations for each invokation of restic. Is this supported or planned? Perhaps multiple instances of the service is the way to go?

**Comment by Southclaws** [comment]
This currently isn't supported, multiple instances probably wouldn't be best as you may end up with lock-contention on the source data. I'm not planning any new features for this tool.
