### ISSUE TITLE
Feature Proposal: add "pre-backup" command

### ISSUE THREAD

**Issue by DrMurx** [Southclaws/restic-robot#3]
Sometimes it would come handy to run a script prior to the scheduled backup, for example to dump a database. Of course, such a dump could happen in a dedicated container, but getting the timing between dump and backup might be difficult.

**Comment by Southclaws** [comment]
Sounds useful! And definitely agree regarding timing.

Though I don't have a use-case for this myself and limited time, I would accept a PR (it would be fairly simple to implement)

Thanks!

**Comment by opthomas-prime** [comment]
Thanks for merging @Southclaws. I haven't changed the README. Maybe the new env variables (https://github.com/Southclaws/restic-robot/blob/master/main.go#L27) should be mentioned.
@DrMurx Does this feature works for you?

**Comment by Southclaws** [comment]
Added to the readme, thanks again for your contribution! I'll close this now :+1:
