### ISSUE TITLE
feature request: ERROR_COMMAND

### ISSUE THREAD

**Issue by lukasmrtvy** [Southclaws/restic-robot#5]
Hello,
( I did not even try this wrapper ), would be nice to have also `ERROR_COMMAND`, which will be triggered if backup will fail. Of course I can probably set up alermanager alert, but 
`ERROR_COMMAND` can be better for handling backup metadata directly from this wrappper.

For example:
`ERROR_COMMAND`: `curl $SLACK_URL -d "Backup $METADATA failed...,because $ERROR"`
`POST_COMMAND`: `curl $SLACK_URL -d "Backup $METADATA success..."`

It can be probably done with https://github.com/healthchecks/healthchecks, but thats another additonal component ( just like prometheus + alertmanager ).

Thanks :)

**Comment by Southclaws** [comment]
Yes, this would be useful. I'd accept a PR, though as I'm not actively working on this at the moment.
